version: "3.8"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env

  frontend:
    build:
      context: ./react_ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
