name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "react_ui/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only react_ui
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
